/**
 * Shared domain types for Creator AI Studio.
 *
 * These describe the production lifecycle of an episode. No real content is
 * produced here — only the type contracts shared across api, web and workers.
 */

/** Ordered lifecycle stages an episode moves through during production. */
export const EPISODE_STATUSES = [
  'draft',
  'scripting',
  'rendering',
  'review',
  'published',
] as const;

/** A single valid episode status. */
export type EpisodeStatus = (typeof EPISODE_STATUSES)[number];

/** Whether episode assets live on VPS disk or were archived to cloud storage. */
export type ArchiveStatus = 'local' | 'archived';

/** Lightweight summary of an episode, suitable for list views and APIs. */
export interface EpisodeSummary {
  /** Stable unique identifier. */
  id: string;
  /** URL-friendly identifier derived from the title. */
  slug: string;
  /** Human-readable episode title. */
  title: string;
  /** Current lifecycle status. */
  status: EpisodeStatus;
  /** ISO-8601 timestamp of when the episode was created. */
  createdAt: string;
  /** ISO-8601 timestamp of the last update. */
  updatedAt: string;
  /** `local` while on VPS; `archived` after Google Drive backup. */
  archiveStatus?: ArchiveStatus;
  /** When the workspace was moved to cloud storage. */
  archivedAt?: string;
  /** Remote path (e.g. rclone remote) after archive. */
  drivePath?: string;
  /** Original VPS folder name (`{id}-{slug}`) for restore from Drive. */
  localWorkspace?: string;
  /** Supabase auth user id when episode was created while logged in. */
  userId?: string;
}

/** Input accepted when creating a new episode. */
export interface CreateEpisodeInput {
  /** Human-readable episode title. The slug is derived from it. */
  title: string;
}

/** Official production stages, in execution order. */
export const EPISODE_STAGES = [
  'planning',
  'research',
  'script',
  'doctrine_review',
  'editorial_review',
  'storyboard',
  'assets',
  'audio',
  'video',
  'subtitles',
  'thumbnail',
  'seo',
  'shorts',
  'final_review',
  'publishing',
  'analytics',
] as const;

/** A single production stage. */
export type EpisodeStage = (typeof EPISODE_STAGES)[number];

/** Allowed statuses for a production stage. */
export const EPISODE_STAGE_STATUSES = [
  'pending',
  'in_progress',
  'completed',
  'blocked',
] as const;

/** A single production stage status. */
export type EpisodeStageStatus = (typeof EPISODE_STAGE_STATUSES)[number];

/**
 * Files each stage is expected to eventually produce, relative to the episode
 * workspace. Descriptive only — no files are created from this map.
 */
export const STAGE_EXPECTED_FILES: Partial<Record<EpisodeStage, string[]>> = {
  research: ['01-research/notes.md'],
  script: ['02-script/script.md'],
  storyboard: ['03-storyboard/storyboard.md', '03-storyboard/scenes.json'],
  assets: ['04-assets/scene-assets.json'],
  audio: ['05-audio/voiceover.mp3', '05-audio/background-music.mp3'],
  video: ['06-video/episode.mp4'],
  subtitles: ['06-subtitles/subtitles.srt'],
  thumbnail: ['07-thumbnail/thumbnail.png'],
  seo: ['08-seo/metadata.json'],
  shorts: ['09-shorts/metadata.json'],
};

/** State of a single production stage. */
export interface EpisodeStageState {
  /** The stage this state refers to. */
  stage: EpisodeStage;
  /** Current status of the stage. */
  status: EpisodeStageStatus;
  /** Files this stage is expected to produce, if any. */
  expectedFiles?: string[];
}

/** A single storyboard scene within an episode. */
export interface Scene {
  id: string;
  /** Human-readable shot concept (Spanish); shown in the storyboard UI. */
  text: string;
  imageUrl: string;
  /** Narration spoken during this scene — never used as image prompt. */
  voiceoverPrompt: string;
  /** Optional concrete visual direction from storyboard agent (Spanish). */
  visualNote?: string;
  /** English Imagen/DALL-E prompt — generated by scene_asset_designer or heuristics. */
  imagePrompt?: string;
  musicTrack: string;
  duration: number;
  transition: string;
}

/** YouTube chapter marker for description / SEO metadata. */
export interface SeoChapter {
  time: string;
  title: string;
}

/** One vertical short derived from a strong moment in the episode. */
export interface EpisodeShort {
  id: string;
  title: string;
  description: string;
  tags?: string[];
  hashtags?: string[];
  scriptText: string;
  /** Start offset in the long-form video (seconds). */
  startTime?: number;
  /** Rendered file relative to workspace, e.g. 09-shorts/short-1.mp4 */
  videoPath?: string;
  youtubeUrl?: string;
}

/** Rich content stored alongside episode metadata. */
export interface EpisodeContent {
  series: string;
  channelId?: string;
  script: string;
  outline: string[];
  scenes: Scene[];
  seoTitles: string[];
  seoDescription: string;
  seoTags: string[];
  /** Chapter markers for YouTube description (00:00 Title). */
  seoChapters?: SeoChapter[];
  /** Suggested pinned comment for YouTube (manual paste — API cannot auto-pin). */
  pinnedComment?: string;
  thumbnailUrl?: string;
  audioUrl?: string;
  /** Authenticated URL for Lyria background music (05-audio/background-music.mp3). */
  musicUrl?: string;
  /** SRT subtitle track generated from scenes or script timing. */
  subtitlesSrt?: string;
  videoUrl?: string;
  /** @deprecated Prefer `shorts` array — kept for legacy single-short episodes. */
  shortsUrl?: string;
  /** Multi-moment shorts produced by shorts_agent + render pipeline. */
  shorts?: EpisodeShort[];
  youtubeVideoId?: string;
  publishConfirmed?: boolean;
  scheduledAt?: string;
  duration: string;
  /** Kanban column override when backend status alone cannot distinguish Ideas vs Investigación. */
  kanbanColumn?: ProjectStatus;
  /** Seed brief from approved ideation — consumed by researcher agent. */
  researchBrief?: string;
  /** Original one-line idea from the ideation workspace. */
  rawIdea?: string;
}

/** Default empty content for a new episode. */
export function createDefaultContent(): EpisodeContent {
  return {
    series: 'Reflexiones',
    script: '',
    outline: [],
    scenes: [],
    seoTitles: [],
    seoDescription: '',
    seoTags: [],
    duration: '00:00',
  };
}

/** Full episode detail: summary metadata plus workspace and stage state. */
export interface EpisodeDetail extends EpisodeSummary {
  /** Path to the episode workspace, relative to the storage root. */
  workspacePath: string;
  /** Production stages with their current status. */
  stages: EpisodeStageState[];
  /** Editable workspace content (script, scenes, SEO, etc.). */
  content: EpisodeContent;
}

/** Partial update for episode metadata and content. */
export interface UpdateEpisodeInput {
  title?: string;
  status?: EpisodeStatus;
  content?: Partial<EpisodeContent>;
}

/** Input accepted when updating a single stage's status. */
export interface UpdateStageInput {
  status: EpisodeStageStatus;
}

/** UI Kanban column labels used by the dashboard. */
export const PROJECT_STATUSES = [
  'Ideas',
  'Investigación',
  'Guion',
  'Narración IA',
  'Edición',
  'Miniatura',
  'Programado',
  'Publicado',
] as const;

export type ProjectStatus = (typeof PROJECT_STATUSES)[number];

/** Map UI Kanban status to backend episode lifecycle status. */
export const PROJECT_TO_EPISODE_STATUS: Record<ProjectStatus, EpisodeStatus> = {
  Ideas: 'draft',
  Investigación: 'draft',
  Guion: 'scripting',
  'Narración IA': 'scripting',
  Edición: 'rendering',
  Miniatura: 'rendering',
  Programado: 'review',
  Publicado: 'published',
};

/** Map backend episode lifecycle status to UI Kanban status. */
export const EPISODE_TO_PROJECT_STATUS: Record<EpisodeStatus, ProjectStatus> = {
  draft: 'Ideas',
  scripting: 'Guion',
  rendering: 'Edición',
  review: 'Programado',
  published: 'Publicado',
};

/** Progress percentage for each episode lifecycle status. */
export const EPISODE_STATUS_PROGRESS: Record<EpisodeStatus, number> = {
  draft: 10,
  scripting: 45,
  rendering: 80,
  review: 95,
  published: 100,
};

/** Type guard for UI project status values. */
export function isProjectStatus(value: unknown): value is ProjectStatus {
  return (
    typeof value === 'string' &&
    (PROJECT_STATUSES as readonly string[]).includes(value)
  );
}

/** Type guard for episode lifecycle status. */
export function isEpisodeStatus(value: unknown): value is EpisodeStatus {
  return (
    typeof value === 'string' &&
    (EPISODE_STATUSES as readonly string[]).includes(value)
  );
}

/** Job types processed by the production worker. */
export const JOB_TYPES = [
  'script',
  'seo',
  'tts',
  'render',
  'thumbnail',
  'shorts',
  'publish',
  'publish_package',
  'archive',
  'pipeline',
  /** Run a specialized agent (payload.agentId required). */
  'agent',
] as const;
export type JobType = (typeof JOB_TYPES)[number];

/** Official specialized agent identifiers. Hermes is the VPS orchestrator. */
export const AGENT_IDS = [
  'hermes',
  'researcher',
  'scriptwriter',
  'doctrine_reviewer',
  'editorial_reviewer',
  'storyboard_designer',
  'scene_asset_designer',
  'narrator',
  'audio_engineer',
  'video_editor',
  'thumbnail_designer',
  'seo_optimizer',
  'shorts_agent',
  'analytics_agent',
] as const;

/** Agents that may pause the pipeline until a human approves the handoff. */
export const HUMAN_APPROVAL_AGENT_IDS = ['doctrine_reviewer', 'editorial_reviewer'] as const;
export type AgentId = (typeof AGENT_IDS)[number];

export type AgentRunStatus = 'running' | 'completed' | 'failed' | 'blocked' | 'awaiting_approval';

/** Quality checks performed by an agent before handoff. */
export interface AgentQualityGate {
  passed: boolean;
  checks: { key: string; label: string; ok: boolean; detail?: string }[];
}

/** Handoff instructions to the next agent or human reviewer. */
export interface AgentHandoff {
  nextAgentId?: AgentId;
  nextStage?: EpisodeStage;
  notes: string;
  requiresHumanApproval?: boolean;
}

/** Persisted record of one agent execution on an episode. */
export interface AgentRunRecord {
  id: string;
  episodeId: string;
  agentId: AgentId;
  status: AgentRunStatus;
  startedAt: string;
  completedAt?: string;
  input?: Record<string, unknown>;
  output?: Record<string, unknown>;
  logs: string[];
  qualityGate?: AgentQualityGate;
  handoff?: AgentHandoff;
  jobId?: string;
}

/** Public agent metadata returned by GET /agents. */
export interface AgentDefinition {
  id: AgentId;
  name: string;
  role: string;
  description: string;
  episodeStage?: EpisodeStage;
  expertise: string[];
  /** Job types this agent may enqueue (Hermes can enqueue all). */
  allowedJobTypes: JobType[];
  status: 'active' | 'planned';
}

export function isAgentId(value: unknown): value is AgentId {
  return typeof value === 'string' && (AGENT_IDS as readonly string[]).includes(value);
}

/** Per-agent customizations persisted in app settings (episode-agnostic). */
export interface AgentOverride {
  /** Free-form notes appended to the system prompt at runtime. */
  customNotes?: string;
  /** Additional skills merged with the agent's base expertise. */
  extraSkills?: string[];
  /** Extra instructions appended after the base system prompt. */
  promptAppend?: string;
}

export type AgentOverridesMap = Partial<Record<AgentId, AgentOverride>>;

/**
 * Pipeline execution modes.
 * - `production-draft`: run every content stage but never touch YouTube.
 * - `ready-for-review`: draft stages + publish package, ends awaiting review.
 * - `publish-authorized`: full pipeline including YouTube upload; requires an
 *   explicit human authorization flag on the job payload.
 */
export const PIPELINE_MODES = [
  'production-draft',
  'ready-for-review',
  'publish-authorized',
] as const;
export type PipelineMode = (typeof PIPELINE_MODES)[number];

export function isPipelineMode(value: unknown): value is PipelineMode {
  return typeof value === 'string' && (PIPELINE_MODES as readonly string[]).includes(value);
}

/** Job lifecycle statuses. */
export const JOB_STATUSES = ['pending', 'active', 'completed', 'failed'] as const;
export type JobStatus = (typeof JOB_STATUSES)[number];

/** A background production job. */
export interface ProductionJob {
  id: string;
  episodeId: string;
  type: JobType;
  status: JobStatus;
  progress: number;
  /** Optional job parameters (e.g. pipeline mode, publish authorization). */
  payload?: Record<string, unknown>;
  result?: Record<string, unknown>;
  error?: string;
  createdAt: string;
  updatedAt: string;
}

/** Input to enqueue a new production job. */
export interface CreateJobInput {
  type: JobType;
  payload?: Record<string, unknown>;
}

/** TTS engine used for narration (configured once in Settings). */
export type TtsProvider = 'elevenlabs' | 'piper' | 'gemini';

/** Single recurring publish slot (day-of-week + time). */
export interface PublishScheduleSlot {
  /** 0 = Sunday … 6 = Saturday */
  dayOfWeek: number;
  hour: number;
  minute: number;
  timezone?: string;
}

/** Recurring publish pattern for long-form and shorts. */
export interface PublishSchedule {
  longVideo: PublishScheduleSlot;
  shorts?: {
    daysOfWeek: number[];
    hour: number;
    minute: number;
    timezone?: string;
  };
}

/** Global application settings persisted by the API. */
export interface AppSettings {
  ttsSampleRate: string;
  ttsAccent: string;
  aiProviderDefault: string;
  /** Preferred narration engine — all TTS from CAS UI uses this. */
  ttsProvider: TtsProvider;
  /** Move workspace to Google Drive after publish is confirmed. */
  autoArchiveOnPublish: boolean;
  /** Max non-archived episodes allowed on VPS disk at once. */
  maxActiveEpisodes: number;
  /** Warn when episode storage exceeds this size (GB). */
  diskWarningThresholdGb: number;
  /** Per-agent prompt/skill overrides from Agent Studio. */
  agentOverrides?: AgentOverridesMap;
  /** YouTube channel ID selected for multichannel operations. */
  activeChannelId?: string;
  /** Recurring publish slots (Camino Bíblico: Mon long, Tue/Thu/Sat shorts). */
  publishSchedule?: PublishSchedule;
}

/** YouTube channel returned by GET /integrations/youtube/channels. */
export interface YouTubeChannelInfo {
  id: string;
  name: string;
  thumbnailUrl: string;
  subscribers: number;
  viewCount: number;
  customUrl?: string;
}

export interface YouTubeChannelsResponse {
  connected: boolean;
  channels: YouTubeChannelInfo[];
}

/** Disk usage snapshot for the operations dashboard. */
export interface StorageStats {
  episodesPath: string;
  totalBytes: number;
  usedBytes: number;
  freeBytes: number;
  episodesBytes: number;
  activeEpisodeCount: number;
  archivedEpisodeCount: number;
  maxActiveEpisodes: number;
  diskWarning: boolean;
  archiveConfigured: boolean;
  ffmpegAvailable: boolean;
  piperAvailable: boolean;
}

/** ElevenLabs voice entry for the narration picker. */
export interface ElevenLabsVoice {
  voiceId: string;
  name: string;
  category?: string;
  previewUrl?: string;
}

/** Result of archiving an episode workspace to cloud storage. */
export interface ArchiveResult {
  ok: boolean;
  drivePath?: string;
  message: string;
}

/** Integration providers that accept API keys or credentials. */
export type SecretProvider =
  | 'gemini'
  | 'openai'
  | 'anthropic'
  | 'elevenlabs'
  | 'youtube'
  | 'webhook';

/** Where a configured secret value was resolved from. */
export type SecretSource = 'store' | 'env' | 'none';

/** How an integration authenticates when configured. */
export type SecretAuthMethod = 'api_key' | 'oauth' | 'none';

/** Masked status of one integration secret (never includes plaintext). */
export interface SecretStatus {
  provider: SecretProvider;
  configured: boolean;
  maskedValue?: string;
  source: SecretSource;
  authMethod?: SecretAuthMethod;
}

/** Writable secret fields (PATCH body). Empty string clears stored value. */
export interface SecretsPatch {
  googleOAuthClientId?: string;
  googleOAuthClientSecret?: string;
  googleOAuthAccessToken?: string;
  googleOAuthRefreshToken?: string;
  googleOAuthExpiresAt?: string;
  googleOAuthScopes?: string;
  geminiApiKey?: string;
  openaiApiKey?: string;
  anthropicApiKey?: string;
  elevenlabsApiKey?: string;
  elevenlabsVoiceId?: string;
  youtubeClientId?: string;
  youtubeClientSecret?: string;
  youtubeAccessToken?: string;
  webhookUrl?: string;
}

/** Result of POST /secrets/test/:provider */
export interface SecretTestResult {
  provider: SecretProvider;
  ok: boolean;
  message: string;
}

/** Channel managed by the platform. */
export interface ChannelRecord {
  id: string;
  name: string;
  type: string;
  status: string;
  subscribers: number;
  avatar: string;
}

export interface CreateChannelInput {
  name: string;
  type: string;
  status?: string;
  subscribers?: number;
  avatar?: string;
}

/** Workspace collaborator role (Equipos). */
export type TeamRole = 'owner' | 'editor' | 'viewer';

export const TEAM_ROLES = ['owner', 'editor', 'viewer'] as const;

/** Active team member persisted by the API. */
export interface TeamMemberRecord {
  id: string;
  userId?: string;
  email: string;
  displayName: string;
  role: TeamRole;
  avatarInitial: string;
  joinedAt: string;
  lastActiveAt?: string;
}

/** Pending email invite before the collaborator signs in. */
export interface TeamInviteRecord {
  id: string;
  email: string;
  role: Exclude<TeamRole, 'owner'>;
  invitedAt: string;
  invitedByUserId?: string;
}

/** Team roster stored in team.json on the API server. */
export interface TeamData {
  ownerUserId?: string;
  members: TeamMemberRecord[];
  invites: TeamInviteRecord[];
}

export interface TeamResponse extends TeamData {
  currentUserId?: string;
  canManage: boolean;
}

export interface SyncTeamOwnerInput {
  email: string;
  displayName: string;
}

export interface CreateTeamInviteInput {
  email: string;
  role: Exclude<TeamRole, 'owner'>;
}

export function isTeamRole(value: unknown): value is TeamRole {
  return typeof value === 'string' && (TEAM_ROLES as readonly string[]).includes(value);
}

export function isJobType(value: unknown): value is JobType {
  return typeof value === 'string' && (JOB_TYPES as readonly string[]).includes(value);
}

/** Type guard: is the given value an official production stage? */
export function isEpisodeStage(value: unknown): value is EpisodeStage {
  return (
    typeof value === 'string' &&
    (EPISODE_STAGES as readonly string[]).includes(value)
  );
}

/** Type guard: is the given value an allowed stage status? */
export function isEpisodeStageStatus(value: unknown): value is EpisodeStageStatus {
  return (
    typeof value === 'string' &&
    (EPISODE_STAGE_STATUSES as readonly string[]).includes(value)
  );
}

/**
 * Simple manual transition rules for the MVP: a stage may move to any other
 * allowed status, but moving to its current status is a no-op and rejected.
 */
export const ALLOWED_STAGE_TRANSITIONS: Record<
  EpisodeStageStatus,
  EpisodeStageStatus[]
> = {
  pending: ['in_progress', 'completed', 'blocked'],
  in_progress: ['completed', 'blocked', 'pending'],
  completed: ['in_progress', 'blocked', 'pending'],
  blocked: ['pending', 'in_progress', 'completed'],
};

/** Whether a manual stage transition from one status to another is allowed. */
export function canTransitionStage(
  from: EpisodeStageStatus,
  to: EpisodeStageStatus,
): boolean {
  return ALLOWED_STAGE_TRANSITIONS[from].includes(to);
}

export {
  DEFAULT_PUBLISH_SCHEDULE,
  formatNextPublishSlot,
  formatPublishScheduleSummary,
  suggestNextPublishSlot,
  type PublishScheduleKind,
} from './schedule.js';

export type {
  CreateIdeaInput,
  EpisodeIdea,
  EpisodeIdeaStatus,
  IdeaProposal,
  IdeaProposalStatus,
} from './ideas.js';
